// <auto-generated />
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DonationsDbContext))]
    [Migration("20260204014858_SeedMissingUsers")]
    partial class SeedMissingUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Donator", b =>
                {
                    b.HasBaseType("Domain.Models.User");

                    b.Property<string>("BloodType")
                        .HasColumnType("text");

                    b.Property<int>("DonationCount")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Donator");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin",
                            IsActive = true,
                            Name = "admin",
                            Password = "$2a$11$N.nB45mfZ.ocViJjnR4ejubZdpw9qaT3lRUn.rrvboIItU5cZFQ0i",
                            Role = 2,
                            DonationCount = 0
                        },
                        new
                        {
                            Id = 4,
                            Email = "gabriel@mail.com",
                            IsActive = true,
                            Name = "Gabriel",
                            Password = "$2a$11$w6L6TmrpQ5lc221kEmWS0..thYqaSiXi5g4FEajiLPXpgNFTHq5WO",
                            Role = 0,
                            DonationCount = 0
                        });
                });

            modelBuilder.Entity("Domain.Models.Requester", b =>
                {
                    b.HasBaseType("Domain.Models.User");

                    b.Property<int>("AdmissionStatus")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Requester");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Email = "gruppesechs@mail.com",
                            IsActive = true,
                            Name = "Gruppe Sechs",
                            Password = "$2a$11$sVDJf6dm5xNO265f9Xjrk.OXPRol.9xTL0gYLtzThgHJ1WepLke7G",
                            Role = 0,
                            AdmissionStatus = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "grupogamma@mail.com",
                            IsActive = true,
                            Name = "Grupo Gamma",
                            Password = "$2a$11$LewVl0EJZyPaFJ43QlpEQOp8YZyqYrCeUFJU8hYMIQVtp0iW.JBsK",
                            Role = 0,
                            AdmissionStatus = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
