// <auto-generated />
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DonationsDbContext))]
    partial class DonationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Account");

                    b.HasDiscriminator<string>("AccountType").HasValue("Account");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Donator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Donator");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "gabriel@mail.com",
                            Name = "Gabriel",
                            Phone = "1234567890123"
                        });
                });

            modelBuilder.Entity("Domain.Models.Requester", b =>
                {
                    b.HasBaseType("Domain.Models.Account");

                    b.Property<int>("AdmissionStatus")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Requester");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Email = "gruppesechs@mail.com",
                            IsActive = true,
                            Name = "Gruppe Sechs",
                            Password = "$2a$11$zfzhWyeQnBPvmZd3Kir3eeE9HoigS5eqioH5R4Ulmf1soMEGQe3Ym",
                            AdmissionStatus = 1
                        });
                });

            modelBuilder.Entity("Domain.Models.Staff", b =>
                {
                    b.HasBaseType("Domain.Models.Account");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin",
                            IsActive = true,
                            Name = "admin",
                            Password = "$2a$11$N7G6W/AvtDo3xJkxWM664eRDmcYulvWvwb.09q5T381GvicCyny4K",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "mod",
                            IsActive = true,
                            Name = "mod",
                            Password = "$2a$11$wRKnnwjzr/zEwV3uUsSuyu3dQxU0Fkv98ejMi334ncv1r8eeTf6PS",
                            Role = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
